/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.Formularios;

import br.com.adilson.util.Extenso;
import br.com.adilson.util.PrinterMatrix;
import conexion.conexion;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurant.Pantallas.Login;

/**
 *
 * @author Obed Martinez
 */
public class caja extends javax.swing.JFrame {
boolean opc=true;
factura fac=new factura();
DefaultTableModel modelo = (DefaultTableModel) fac.tblVentas.getModel();
    /**
     * Creates new form caja
     */
    public caja() {
        initComponents();
        setTitle("Tickets");
        setLocationRelativeTo(null);
        URL url= getClass().getResource("/Imagenes/logo.png");
        ImageIcon img= new ImageIcon(url);
        setIconImage(img.getImage());
        ocultos();
        combos();
        productos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jved = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tickets");

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Ticket");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Platillo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Costo");

        jTextField2.setEditable(false);
        jTextField2.setText("0");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setText("0");

        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setText("0");

        jTextField8.setEditable(false);
        jTextField8.setText("0");

        jTextField10.setEditable(false);
        jTextField10.setText("0");

        jTextField12.setEditable(false);
        jTextField12.setText("0");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Nuevo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Nuevo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setText("Costo neto");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("IVA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Propina");

        jTextField21.setEditable(false);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Precio");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Cobrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Precio");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Precio");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setText("Precio");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setText("Precio");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton15.setText("Precio");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel11.setText("Vendedor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jved, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 93, Short.MAX_VALUE)))
                            .addGap(135, 135, 135)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(241, 241, 241)
                            .addComponent(jButton1)))
                    .addGap(158, 158, 158)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(40, 40, 40))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(5, 5, 5))
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4)
                                        .addComponent(jButton7)
                                        .addComponent(jButton6)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton11)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton13)
                                            .addGap(19, 19, 19)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jButton15)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jved, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(jButton15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(jButton13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14)
                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton8)
                        .addComponent(jButton9))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(opc == true){    
            fac.setVisible(true);
            float a,b,c,d,e,f,k,l,m,n;
        a=Float.parseFloat(jTextField2.getText());
        b=Float.parseFloat(jTextField4.getText());
        c=Float.parseFloat(jTextField6.getText());
        d=Float.parseFloat(jTextField8.getText());
        e=Float.parseFloat(jTextField10.getText());
        f=Float.parseFloat(jTextField12.getText());
        k=a+b+c+d+e+f;
        l=(float) (k*.16);
        m=(float) (k*.10);
        n=k+l+m;
            fac.jTextField7.setText(String.valueOf(n));
            opc=false;
            String nom=jved.getText();
            fac.jLabel7.setText(nom);
            tabla();
        }else{
            fac.dispose();
            opc=true;
            fac.setVisible(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jComboBox2.setVisible(true);
    jTextField3.setVisible(true);
    jTextField4.setVisible(true);
    jButton3.setVisible(true);
    jButton13.setVisible(true);
    String nom;
    int cant;
    cant=Integer.parseInt(jTextField1.getText());
    nom = (String) jComboBox1.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField2.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    jComboBox3.setVisible(true);
    jTextField5.setVisible(true);
    jTextField6.setVisible(true);
    jButton4.setVisible(true);
    jButton12.setVisible(true);
    String nom;
    int cant;
    cant=Integer.parseInt(jTextField3.getText());
    nom = (String) jComboBox2.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField4.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    jComboBox4.setVisible(true);
    jTextField7.setVisible(true);
    jTextField8.setVisible(true);
    jButton5.setVisible(true);
    jButton11.setVisible(true);
    String nom;
    int cant;
    cant=Integer.parseInt(jTextField5.getText());
    nom = (String) jComboBox3.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField6.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    jComboBox5.setVisible(true);
    jTextField9.setVisible(true);
    jTextField10.setVisible(true);
    jButton6.setVisible(true);
    jButton10.setVisible(true);
    String nom;
    int cant;
    cant=Integer.parseInt(jTextField7.getText());
    nom = (String) jComboBox4.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField8.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    jComboBox6.setVisible(true);
    jTextField11.setVisible(true);
    jTextField12.setVisible(true);
    jButton7.setVisible(true);
    String nom;
    int cant;
    cant=Integer.parseInt(jTextField9.getText());
    nom = (String) jComboBox5.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField10.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        float a,b,c,d,e,f,k,l,m,n;
        a=Float.parseFloat(jTextField2.getText());
        b=Float.parseFloat(jTextField4.getText());
        c=Float.parseFloat(jTextField6.getText());
        d=Float.parseFloat(jTextField8.getText());
        e=Float.parseFloat(jTextField10.getText());
        f=Float.parseFloat(jTextField12.getText());
        k=a+b+c+d+e+f;
        jLabel5.setText(String.valueOf(k));
        l=(float) (k*.16);
        jLabel6.setText(String.valueOf(l));
        m=(float) (k*.10);
        jLabel10.setText(String.valueOf(m));
        n=k+l+m;
        jTextField21.setText(String.valueOf(n));
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String nom;
    int cant;
    cant=Integer.parseInt(jTextField11.getText());
    nom = (String) jComboBox6.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField12.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Login log=new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String p1,p2,p3,p4,p5,p6,plaf;
        String c1,c2,c3,c4,c5,c6,cf;
        String cs1,cs2,cs3,cs4,cs5,cs6,csf;
        float tot,iva,prop,net;
        if(jButton7.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            p2=(String) jComboBox2.getSelectedItem();
            p3=(String) jComboBox3.getSelectedItem();
            p4=(String) jComboBox4.getSelectedItem();
            p5=(String) jComboBox5.getSelectedItem();
            p6=(String) jComboBox6.getSelectedItem();
            plaf=p1+","+p2+","+p3+","+p4+","+p5+","+p6;
            c1=jTextField1.getText();
            c2=jTextField3.getText();
            c3=jTextField5.getText();
            c4=jTextField7.getText();
            c5=jTextField9.getText();
            c6=jTextField11.getText();
            cf=c1+","+c2+","+c3+","+c4+","+c5+","+c6;
            cs1=jTextField2.getText();
            cs2=jTextField4.getText();
            cs3=jTextField6.getText();
            cs4=jTextField8.getText();
            cs5=jTextField10.getText();
            cs6=jTextField12.getText();
            csf=cs1+","+cs2+","+cs3+","+cs4+","+cs5+","+cs6;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            jComboBox5.setSelectedIndex(0);
            jComboBox6.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }else if(jButton6.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            p2=(String) jComboBox2.getSelectedItem();
            p3=(String) jComboBox3.getSelectedItem();
            p4=(String) jComboBox4.getSelectedItem();
            p5=(String) jComboBox5.getSelectedItem();
            plaf=p1+","+p2+","+p3+","+p4+","+p5;
            c1=jTextField1.getText();
            c2=jTextField3.getText();
            c3=jTextField5.getText();
            c4=jTextField7.getText();
            c5=jTextField9.getText();
            cf=c1+","+c2+","+c3+","+c4+","+c5;
            cs1=jTextField2.getText();
            cs2=jTextField4.getText();
            cs3=jTextField6.getText();
            cs4=jTextField8.getText();
            cs5=jTextField10.getText();
            csf=cs1+","+cs2+","+cs3+","+cs4+","+cs5;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            jComboBox5.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
            
        }else if(jButton5.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            p2=(String) jComboBox2.getSelectedItem();
            p3=(String) jComboBox3.getSelectedItem();
            p4=(String) jComboBox4.getSelectedItem();
            plaf=p1+","+p2+","+p3+","+p4;
            c1=jTextField1.getText();
            c2=jTextField3.getText();
            c3=jTextField5.getText();
            c4=jTextField7.getText();
            cf=c1+","+c2+","+c3+","+c4;
            cs1=jTextField2.getText();
            cs2=jTextField4.getText();
            cs3=jTextField6.getText();
            cs4=jTextField8.getText();
            csf=cs1+","+cs2+","+cs3+","+cs4;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            jComboBox4.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        else if(jButton4.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            p2=(String) jComboBox2.getSelectedItem();
            p3=(String) jComboBox3.getSelectedItem();
            plaf=p1+","+p2+","+p3;
            c1=jTextField1.getText();
            c2=jTextField3.getText();
            c3=jTextField5.getText();
            cf=c1+","+c2+","+c3;
            cs1=jTextField2.getText();
            cs2=jTextField4.getText();
            cs3=jTextField6.getText();
            csf=cs1+","+cs2+","+cs3;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }else if(jButton3.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            p2=(String) jComboBox2.getSelectedItem();
            plaf=p1+","+p2;
            c1=jTextField1.getText();
            c2=jTextField3.getText();
            cf=c1+","+c2;
            cs1=jTextField2.getText();
            cs2=jTextField4.getText();
            csf=cs1+","+cs2;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }else if(jButton2.isVisible()==true){
            p1=(String) jComboBox1.getSelectedItem();
            plaf=p1;
            c1=jTextField1.getText();
            cf=c1;
            cs1=jTextField2.getText();
            csf=cs1;
            tot=Float.parseFloat(jLabel5.getText());
            iva=Float.parseFloat(jLabel6.getText());
            prop=Float.parseFloat(jLabel10.getText());
            net=Float.parseFloat(jTextField21.getText());
            Connection conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
            String sql = "INSERT INTO tickets(no_tick,platillos,cantidad,costo,total,iva,prop,neto) VALUES(?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement pst  = conn.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, plaf);
            pst.setString(3, cf);
            pst.setString(4, csf);
            pst.setFloat(5, tot);
            pst.setFloat(6, iva);
            pst.setFloat(7, prop);
            pst.setFloat(8, net);;
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(this, "Ticket realizado");
            jTextField1.setText("");
            jTextField2.setText("");
            jComboBox1.setSelectedIndex(0);
            }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String nom;
    int cant;
    cant=Integer.parseInt(jTextField9.getText());
    nom = (String) jComboBox5.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField10.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String nom;
    int cant;
    cant=Integer.parseInt(jTextField7.getText());
    nom = (String) jComboBox4.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField8.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
                                           
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String nom;
    int cant;
    cant=Integer.parseInt(jTextField5.getText());
    nom = (String) jComboBox3.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField6.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String nom;
    int cant;
    cant=Integer.parseInt(jTextField3.getText());
    nom = (String) jComboBox2.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField4.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
String nom;
    int cant;
    cant=Integer.parseInt(jTextField1.getText());
    nom = (String) jComboBox1.getSelectedItem();
    Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas WHERE nombre='"+nom+"'";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                String pre = rs.getString("cost");
                Double preu = Double.valueOf(pre);
                double tot = preu*cant;
                jTextField2.setText(String.valueOf(tot));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JLabel jved;
    // End of variables declaration//GEN-END:variables

    private void combos() {
        jComboBox1.addItem("Selecciona el platillo");
        jComboBox2.addItem("Selecciona el platillo");
        jComboBox3.addItem("Selecciona el platillo");
        jComboBox4.addItem("Selecciona el platillo");
        jComboBox5.addItem("Selecciona el platillo");
        jComboBox6.addItem("Selecciona el platillo");
    }

    private void ocultos() {
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox4.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton1.setEnabled(false);
        jButton7.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
    }

    private void productos() {
        Connection conn;
        conn = conexion.getConnection(); //Para tener conexión a la Base de Datos.
        ResultSet rs;
        String sql="SELECT * FROM recetas";
        try {
            Statement sqls=conn.prepareStatement(sql);
            rs=sqls.executeQuery(sql);
            
            while(rs.next()){
                jComboBox1.addItem(rs.getString("nombre"));
                jComboBox2.addItem(rs.getString("nombre"));
                jComboBox3.addItem(rs.getString("nombre"));
                jComboBox4.addItem(rs.getString("nombre"));
                jComboBox5.addItem(rs.getString("nombre"));
                jComboBox6.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formprod.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void tabla() {
        
        if(jButton7.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        Object [] fila2=new Object[3];
        fila2[0]=jComboBox2.getSelectedItem().toString();
        fila2[1]=jTextField3.getText();
        fila2[2]=jTextField4.getText();
        modelo.addRow(fila2);
        Object [] fila3=new Object[3];
        fila3[0]=jComboBox3.getSelectedItem().toString();
        fila3[1]=jTextField5.getText();
        fila3[2]=jTextField6.getText();
        modelo.addRow(fila3);
        Object [] fila4=new Object[3];
        fila4[0]=jComboBox4.getSelectedItem().toString();
        fila4[1]=jTextField7.getText();
        fila4[2]=jTextField8.getText();
        modelo.addRow(fila4);
        Object [] fila5=new Object[3];
        fila5[0]=jComboBox5.getSelectedItem().toString();
        fila5[1]=jTextField9.getText();
        fila5[2]=jTextField10.getText();
        modelo.addRow(fila5);
        Object [] fila6=new Object[3];
        fila6[0]=jComboBox6.getSelectedItem().toString();
        fila6[1]=jTextField11.getText();
        fila6[2]=jTextField12.getText();
        modelo.addRow(fila6);
        fac.tblVentas.setModel(modelo);
        }
        else if(jButton6.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        Object [] fila2=new Object[3];
        fila2[0]=jComboBox2.getSelectedItem().toString();
        fila2[1]=jTextField3.getText();
        fila2[2]=jTextField4.getText();
        modelo.addRow(fila2);
        Object [] fila3=new Object[3];
        fila3[0]=jComboBox3.getSelectedItem().toString();
        fila3[1]=jTextField5.getText();
        fila3[2]=jTextField6.getText();
        modelo.addRow(fila3);
        Object [] fila4=new Object[3];
        fila4[0]=jComboBox4.getSelectedItem().toString();
        fila4[1]=jTextField7.getText();
        fila4[2]=jTextField8.getText();
        modelo.addRow(fila4);
        Object [] fila5=new Object[3];
        fila5[0]=jComboBox5.getSelectedItem().toString();
        fila5[1]=jTextField9.getText();
        fila5[2]=jTextField10.getText();
        modelo.addRow(fila5);
        fac.tblVentas.setModel(modelo);
        }
        else if(jButton5.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        Object [] fila2=new Object[3];
        fila2[0]=jComboBox2.getSelectedItem().toString();
        fila2[1]=jTextField3.getText();
        fila2[2]=jTextField4.getText();
        modelo.addRow(fila2);
        Object [] fila3=new Object[3];
        fila3[0]=jComboBox3.getSelectedItem().toString();
        fila3[1]=jTextField5.getText();
        fila3[2]=jTextField6.getText();
        modelo.addRow(fila3);
        Object [] fila4=new Object[3];
        fila4[0]=jComboBox4.getSelectedItem().toString();
        fila4[1]=jTextField7.getText();
        fila4[2]=jTextField8.getText();
        modelo.addRow(fila4);
        fac.tblVentas.setModel(modelo);
        }
        else if(jButton4.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        Object [] fila2=new Object[3];
        fila2[0]=jComboBox2.getSelectedItem().toString();
        fila2[1]=jTextField3.getText();
        fila2[2]=jTextField4.getText();
        modelo.addRow(fila2);
        Object [] fila3=new Object[3];
        fila3[0]=jComboBox3.getSelectedItem().toString();
        fila3[1]=jTextField5.getText();
        fila3[2]=jTextField6.getText();
        modelo.addRow(fila3);
        fac.tblVentas.setModel(modelo);
        }
        else if(jButton3.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        Object [] fila2=new Object[3];
        fila2[0]=jComboBox2.getSelectedItem().toString();
        fila2[1]=jTextField3.getText();
        fila2[2]=jTextField4.getText();
        modelo.addRow(fila2);
        fac.tblVentas.setModel(modelo);
        }
        else if(jButton2.isVisible()==true){
        Object [] fila1=new Object[3];
        fila1[0]=jComboBox1.getSelectedItem().toString();
        fila1[1]=jTextField1.getText();
        fila1[2]=jTextField2.getText();
        modelo.addRow(fila1);
        fac.tblVentas.setModel(modelo);
    }
    }
    
}
